language: python
python:
  - "3.4"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database masterfirefoxos_db;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - DEBUG=False SECRET_KEY='FOO' ALLOWED_HOSTS=localhost, DATABASE_URL=postgres://postgres@localhost/masterfirefoxos_db
script:
  flake8 masterfirefoxos && coverage run manage.py test
after_success:
  coveralls
